### ISSUE TITLE
IOException instead of RuntimeException?

### ISSUE THREAD

**Issue by swankjesse** [tir38/android-network-monkey#1]
OkHttp shouldn’t throw RuntimeExceptions during normal operation. If it does, that's a severe bug that we'll fix urgently.

Wanna change the monkey​ to throw IOExceptions instead? They're definitely something developers need to handle.

**Comment by tir38** [comment]
Absolutely. I wasn't sure if there was one parent exception that encompassed all exceptions OkHttp might throw.

**Comment by tir38** [comment]
Done.
